### ISSUE TITLE
Rtl issue 

### ISSUE THREAD

**Issue by NahumG10** [roto93/react-native-neat-date-picker#12]
[CamScanner 04-08-2022 13.57.pdf](https://github.com/roto93/react-native-neat-date-picker/files/8451222/CamScanner.04-08-2022.13.57.pdf)
Hi, my app is running on right to left mode, and it seems that the date picker arrows and direction flips, is there a way to fix it?

**Comment by roto93** [comment]
Interesting. I didn't know that there is a RTL mode in phone. Thanks for issueing this.
Since I'm not familiar with RTL mode, is there anything has to fix beside the icon direction issue you mentioned? For example, is the direction of dates correct in your image? And what should be the perfect layout for this date picker in RTL mode?

**Comment by NahumG10** [comment]
I would prefer to have exactly the same layout as the original you created. Everything flipped in my date picker and it's weird to use lol

**Comment by roto93** [comment]
Got it. I will try fixing this next weekend

**Comment by NahumG10** [comment]
Thanks a lot, I appreciate it!

**Comment by roto93** [comment]
Hi, I've tried to ignore the RTL setting in user's phone. Could you update the date picker to the latest version and test if your issue is solved?

**Comment by NahumG10** [comment]
Hi, that doesn't seem to fix it but I tried modifying the code a bit and it works fine now, Thanks! Just to know, are you working on a time picker as well? Because your date picker is wondeful and I'd like to use a time picker in my app with same styling and functionality and your datepicker..

**Comment by roto93** [comment]
Sorry I have been fulfilling the military service in my country therefore could not reply for weeks. 
Glad to hear that you solved it. Just curious how did you do it?
Thank you for loving this date picker. Unfortunately I didn’t working on time picker. But if I have time I will give it a try.

**Comment by roto93** [comment]
Closing because no activities. Feel free to reopen it.
