### ISSUE TITLE
This pkg have expo compatibility?

### ISSUE THREAD

**Issue by diecodev** [roto93/react-native-neat-date-picker#15]
Hi, can you please tell me if this package is compatible with expo for Android and IOS?

**Comment by roto93** [comment]
Yes, it is compatible with both expo and bare workflow. Regardless of platforms

**Comment by diecodev** [comment]
Bro, you should update this package dependecies. I can do it if you are agree. When you use this component into an Expo app, it display alert message when the component is unmounted.

**Comment by roto93** [comment]
Hi, I just updated the dependency. I believe the warning is gone in the latest version.
Please update this package to the latest version and check if the issue is still exists.

**Comment by diecodev** [comment]
@roto93 I recently update this pkg and you are right, now the warning is gone! Thank you bro, this pkg is all I need. Hope it make popular.
