### ISSUE TITLE
Add React import

### ISSUE THREAD

**Issue by blorent** [roto93/react-native-neat-date-picker#21]
Hi,
I'm testing out your date picker. Small issue, I had to add imports of "React from 'react'" in all your tsx files in order to make it work with my project.  Maybe I did something wrong when including it, but it solved the issue

**Comment by roto93** [comment]
Hi, thank you for reporting this. 
What is the version of React you are using? 
If it is earlier than React 17 then it's necessary to import react manually.
But that reminds me not all projects use the latest version so I will update the package these days.

**Comment by cunger** [comment]
Strange; I get the error "Can't find variable: React" with the following versions:
```
"react": "18.1.0",
"react-native": "0.70.5",
"react-native-neat-date-picker": "^1.4.7",
```
It points to `NeatDatePicker.tsx` line 313 (where you use `Modal`).

**Comment by roto93** [comment]
Sorry, got busy on other stuff. thanks to [drisbhi](https://github.com/drisbhi)'s PR #25 that added the react import
