### ISSUE TITLE
Using the date picker without a <Modal>

### ISSUE THREAD

**Issue by rbozan** [roto93/react-native-neat-date-picker#27]
Hi,

We'd like to use the date picker without it wrapped within a `<Modal>`. So just the date picker itself. Is this possible?

Basically everything which is wrapped within `<Modal>`:
https://github.com/roto93/react-native-neat-date-picker/blob/b1e5be8c45ac98c038b846a939e6cb2eab3b36d0/src/components/NeatDatePicker.tsx#L334

**Comment by roto93** [comment]
Hi, I have added a new prop `withoutModal` in the latest version 1.4.11
I just simply pull out every thing inside the modal but it looks weird. 
There should be more style customization to make it better but I'm afraid I don't have much time to do it...
