### ISSUE TITLE
 Unable to resolve module ./src/components/NeatDatePicker 

### ISSUE THREAD

**Issue by rahmanharoon** [roto93/react-native-neat-date-picker#4]
Followed the documentation and getting this error
```
Error: Unable to resolve module ./src/components/NeatDatePicker from /Users/rahmanharoon/Desktop/nextport-sub-contractor-mobile/node_modules/react-native-neat-date-picker/index.js:
None of these files exist:
  * node_modules/react-native-neat-date-picker/src/components/NeatDatePicker(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * node_modules/react-native-neat-date-picker/src/components/NeatDatePicker/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
> 1 | import DatePicker from './src/components/NeatDatePicker'
    |                         ^
  2 |
  3 | export default DatePicker
```

Tried removing node_modules, package-lock.json, pod files and pod.lock and still getting this issue

**Comment by roto93** [comment]
Hi, thank you for reporting this issue.
Unfortunately, I don't see any possible reason to cause this error. 
I tried this package early today from a brand new RN project but it seems ok.
Could you provide more information like the version and environment you're using. A minimum reproduction code would be great.

btw, I found a serious mistake in my README example code. I've already fixed it. Maybe you can try it out.

**Comment by nescroft** [comment]
Looks cool. I have the same error though. Hmmm.

**Comment by roto93** [comment]
Intresting. Thanks for the advise @nescroft  . I didn't think about this possibility.
I thought that .jsx and .js are totally the same :P
Seems like either I change all the .jsx extension to .js or users modify their config [like this](https://github.com/facebook/react-native/pull/5233#issuecomment-442279996) will fix it.
Could you try out the latter to see if it works? Since I can not encounter this error.
If the error persists, I'll change the extensions.

**Comment by nescroft** [comment]
> Intresting. Thanks for the advise @nescroft . I didn't think about this possibility.
> I thought that .jsx and .js are totally the same :P
> Seems like either I change all the .jsx extension to .js or users modify their config [like this](https://github.com/facebook/react-native/pull/5233#issuecomment-442279996) will fix it.
> Could you try out the latter to see if it works? Since I can not encounter this error.
> If the error persists, I'll change the extensions.

@roto93 nice! maybe @rahmanharoon  can try it. I decided to use a different repo and I'm trying to meet a deadline at the moment. If it is not a big deal to change to .js that is probably the best solution.

**Comment by roto93** [comment]
You're right! It should be quite quick. I'll do this later.

**Comment by roto93** [comment]
Hi @nescroft @rahmanharoon Just to let you know that I have change the extension to .js and update the package.
Feel free to test it when you have time, and let me know if the error still exists.

**Comment by rahmanharoon** [comment]
Yea sure, I will check this and give you an update on this asap..

**Comment by roto93** [comment]
Oh! Seems like I missed this dependency. Can a react-native-cli project use @expo/vector-icons? I made this package from a expo project so there are some @expo packages in it.
Or maybe I should change another library like [react-native-vector-icon](https://github.com/oblador/react-native-vector-icons)

**Comment by rahmanharoon** [comment]
I was getting module not found error one by one 
here is the list of dependency i have added
```
expo-font,
@unimodules/core,
expo-constants,
expo-asset ,
@unimodules/react-native-adapter,
expo-file-system 
```

After that app loaded and after clicking on button the calendar modal is not opening..I can confirm state of showDatePicker is changing whenever i click on button..

Also am getting 5 warning on console you can find them on here https://github.com/rahmanharoon/neat-date-picker-demo

**Comment by roto93** [comment]
Hi, I've just update the package to v1.1.1. Now it should work.
What I have done is removing all the expo-related packages and using react-native-vector-icons instead.
I've checked that react-native-cli project can use it with no error. Could you reinstall it again to see if it works?

**Comment by roto93** [comment]
Also, no need to manually install any dependency now.
